### ISSUE TITLE
problem with test

### ISSUE THREAD

**Issue by kaleba** [litesync/uv_callback#2]
Dear friends

If I run test for say 10 times, 5 or 6 times I receive error like this:

[root@xms test]# ./test
uv_callback_init rc=0
uv_callback_init rc=0
uv_callback_init rc=0
uv_callback_init rc=0
uv_callback_init rc=0
uv_callback_init rc=0
running the event loop in the main thread
progress: 99 %
static pointer: (0x401fd8) Hello World!
dynamic pointer: (0x1f74340) The fourth message
sum (0x1f74400) number1: 123  number2: 456
sum result: 579
sum result (0x7fc6f0000950)  number1: 123  number2: 456  result=579
cleaning up the main thread
test: test.c:207: main: Assertion `static_call_counter == 3' failed.
Aborted (core dumped)
[root@xms test]#

I'm using libuv 1.9.1 on CentOS 6.5 with kernel 2.6.32

Any idea what to do?

Best Regards

**Comment by kroggen** [comment]
Hi!

Thank you for reporting that!

Indeed it is failing sometimes. In my tests I noticed that the callbacks are fired in the worker thread, but only after the assertion in the main thread. The assertion should occur after the calls.

This behavior was introduced in the last commit, that is affecting the order of calls.

I will check how to solve that.

**Comment by kroggen** [comment]
I made a new version that preserves the order of calls.

Could you test it on your platform?

**Comment by kaleba** [comment]
Hi!

Now it is working as expected. Thank You for Your effort.

I call test more than 1000 times with no one error.

I'm new to libuv. My I ask You some beginners question?

Best Regards

**Comment by kroggen** [comment]
Nice!

I guess the best place for questions (after checking the [docs](http://docs.libuv.org)) is [here](https://github.com/libuv/help) or in the [forum](https://groups.google.com/d/forum/libuv)

I have commercial consulting by e-mail if you want.

Happy coding!
