### ISSUE TITLE
uv_mutex_lock causing Access violation writing

### ISSUE THREAD

**Issue by gamelaster** [litesync/uv_callback#4]
Hello,

I used uv_callback in my app. Everything works awesome until I recloned and cleaned my project, after that I everytime get an access violation at uv_callback_fire.c:141 .

Any ideas where could be a problem?

**Comment by kroggen** [comment]
Hi Marek!

I was not able to reproduce the error.

Have you modified the uv_callback.c file?

**Comment by gamelaster** [comment]
I didn't changed uv_callback.c . Also, when I changed to UV_COALESCE, it's started working. I using this in my NodeJS embedded app, and I don't know why but on example .exe file it's working with UV_NORMAL, so no idea why normal doesn't work

**Comment by kroggen** [comment]
UV_COALESCE will make your calls to coalesce. Use it only if you are passing data by value, not with pointers to allocated data.

I did not understand: "so no idea why _normal_ doesn't work".

Note that the constant is `UV_DEFAULT`

**Comment by gamelaster** [comment]
Sorry, with normal I meaned UV_DEFAULT.

The UV_DEFAULT works long time without any problems (I sending pointer to allocated data), now I just changed it to coalesce and it's starts working again (but still sending a pointer to allocated data). Well, when I can use the UV_DEFAULT, I probably must change it to pass data not pointer. Just I can't get how something what works without any problem stops after deleting and cloning project repository.

**Comment by kroggen** [comment]
You could be using the [previous version](https://github.com/litesync/uv_callback/tree/f19aba8b9c21f860f9e00fd5654baa6aeff81a76) before, and the cloning always return the last version.

I cannot reproduce the error you are experiencing with the last version.

Could you make a simple example that reproduces the error and post the source here?

Inform also the OS and platform used.

**Comment by gamelaster** [comment]
I think I use the same version, it's only 20 days what I using it. Windows 10 x64, NodeJS v7.10.0 .

Example code etc. I will send you when I arrive home (2 days)

For now thanks

**Comment by brucejee** [comment]
I also met coredump in uv_callback.c 141 line. And I commit a pull request [here](https://github.com/litesync/uv_callback/pull/7)

**Comment by brucejee** [comment]
Use uv_callback_fire must notice notify handle and its loop must valid before notify's uv_callback_func called. This pull request doesn't fix all bad usecases.

**Comment by kroggen** [comment]
Hi!

Could you make a simple example that reproduces the error and post the source here?

Inform also the OS in which the problem occurs.

**Comment by brucejee** [comment]
I change test.c, and output this coredump, 0x7fffffffd7a0 is the local var notify in uv_callback_fire_sync.
And add log "uv_callback_fire_sync local var notify:0x7fffffffd7a0" in uv_callback_fire_sync.

coredump has this frame:
```
#4  0x00000000004013fc in uv_callback_fire (callback=0x7fffffffd7a0, data=0x14d, notify=0x0) at ../uv_callback.c:150
```
```
uv_callback_init rc=0
uv_callback_init rc=0
uv_callback_init rc=0
running the event loop in the main thread
progress: 99 %
static pointer: (0x402213) Hello World!
static pointer: (0x402220) How you doing?
static pointer: (0x402230) I'm programming with libuv! :P
dynamic pointer: (0x6040a0) The fourth message
dynamic pointer: (0x6042a0) The fifth message
dynamic pointer: (0x6042f0) The sixth message
sum1 (0x604340) number1: 123  number2: 456  result: 579
on sum result (0x7ffff0000d60)  number1: 123  number2: 456  result=579
cleaning up the main thread
uv_callback_fire_sync local var notify:0x7fffffffd7a0
sum1 (0x604340) number1: 111  number2: 222  result: 333
uv_callback_fire_sync rc=-110
response=(nil)
uv_callback_fire_sync local var notify:0x7fffffffd7a0
sum2 (0x604340) number1: 111  number2: 222  result: 333
uv_callback_fire_sync rc=0
result=-268432032

Thread 2 "test_new" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff71bf700 (LWP 16936)]
0x00007ffff781e428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff781e428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff782002a in __GI_abort () at abort.c:89
#2  0x00007ffff7bbd332 in uv__async_send (wa=<optimized out>) at src/unix/async.c:177
#3  0x00007ffff7bbd384 in uv_async_send (handle=<optimized out>) at src/unix/async.c:66
#4  0x00000000004013fc in uv_callback_fire (callback=0x7fffffffd7a0, data=0x14d, notify=0x0) at ../uv_callback.c:150
#5  0x0000000000401129 in uv_callback_async_cb (handle=0x603880 <cb_static_pointer>) at ../uv_callback.c:63
#6  0x00000000004011d7 in uv_callback_idle_cb (handle=0x603948 <cb_static_pointer+200>) at ../uv_callback.c:84
#7  0x00007ffff7bc3334 in uv__run_idle (loop=loop@entry=0x7ffff71bebd0) at src/unix/loop-watcher.c:68
#8  0x00007ffff7bbda38 in uv_run (loop=0x7ffff71bebd0, mode=UV_RUN_DEFAULT) at src/unix/core.c:347
#9  0x0000000000401b75 in worker_start (arg=0x0) at test_new.c:120
#10 0x00007ffff7bc89d7 in uv__thread_start (arg=<optimized out>) at src/unix/thread.c:52
#11 0x00007ffff73cb6ba in start_thread (arg=0x7ffff71bf700) at pthread_create.c:333
#12 0x00007ffff78f03dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb)
```

Change test.c file as follows:
```
--- test.c	2018-05-23 18:50:42.874000000 +0800
+++ test_new.c	2018-05-23 19:02:49.466309796 +0800
@@ -3,6 +3,7 @@
 #include <memory.h>
 #include "../uv_callback.c"
 #include <assert.h>
+#include <unistd.h>
 
 uv_thread_t   worker_thread;
 uv_barrier_t  barrier;
@@ -65,6 +66,7 @@
    response->result = request->number1 + request->number2;
    printf("sum1 (%p) number1: %d  number2: %d  result: %d\n", data, request->number1, request->number2, response->result);
    free(request);
+   sleep(2);
    return response;
 }
 
@@ -219,12 +221,12 @@
    req->result = 0;
 
    /* call the function in the other thread */
-   rc = uv_callback_fire_sync(&cb_sum, req, (void**)&resp, 10000);
+   rc = uv_callback_fire_sync(&cb_sum, req, (void**)&resp, 1000);
    printf("uv_callback_fire_sync rc=%d\n", rc);
-   assert(rc == 0);
+   // assert(rc == 0);
    printf("response=%p\n", resp);
-   assert(resp != 0);
-   assert(resp->result == 333);
+   // assert(resp != 0);
+   // assert(resp->result == 333);
    free(resp);
 
    /* allocate memory fo the arguments */
@@ -237,9 +239,9 @@
    /* call the function in the other thread - this one returns an integer */
    rc = uv_callback_fire_sync(&cb_sum2, req, (void**)&result, 10000);
    printf("uv_callback_fire_sync rc=%d\n", rc);
-   assert(rc == 0);
+   // assert(rc == 0);
    printf("result=%d\n", result);
-   assert(result == 333);
+   // assert(result == 333);
 
    /* send a signal to the worker thread to exit */
    uv_callback_fire(&stop_worker, NULL, NULL);
```

**Comment by kroggen** [comment]
Sorry for the late response.

I made a fix. Please inform if you find any other problem.

Thank you for informing!
